name: PublishToPyPI

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry Run
        required: false
        default: false
        type: boolean

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Build
      run: uv build

    - name: Publish to PyPI
      if: ${{ !inputs.dry_run }}
      run: uv publish --token ${{ env.PYPI_TOKEN }}
