name: PublishToTestPyPI

on:
  workflow_dispatch

env:
  TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Build
      run: uv build

    - name: Publish to TestPyPI
      run: uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ env.TEST_PYPI_TOKEN }}
