name: PublishToPyPI

on:
  workflow_dispatch:

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Build
      run: uv build

    - name: Publish to PyPI
      run: uv publish --token ${{ env.PYPI_TOKEN }}
