name: PublishToTestPyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        default: dry-run
        type: string

env:
  TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Git Tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag ${{ github.event.inputs.tag }}
        git push https://x-access-token:${{ env.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }} ${{ github.event.inputs.tag }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Build
      run: uv build

#    - name: Publish to TestPyPI
#      run: uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ env.TEST_PYPI_TOKEN }}
