name: PythonTest

on:
  pull_request:
    branches:
      - main  # ここでPRをトリガーするブランチを指定

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Run lint
      run: uv run task lint --output-format=github

    - name: Run format
      run: uv run task format --check

    - name: Run tests
      run: uv run task test